<?xml version="1.0" encoding="UTF-8"?>

<definitions name="UniversalRecordServices"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.travelport.com/service/universal_v47_0"
             xmlns:ns1="http://www.travelport.com/schema/universal_v47_0"
             targetNamespace="http://www.travelport.com/service/universal_v47_0">

    <import namespace="http://www.travelport.com/service/universal_v47_0"
            location="UniversalRecordAbstract.wsdl"/>

    <binding name="UniversalRecordRetrieveServiceBinding" type="tns:UniversalRecordRetrieveServicePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="service">
            <soap:operation soapAction="http://localhost:8080/kestrel/UniversalRecordService"/>
            <input>
            	<soap:header use="literal" part="sessionContext" message="tns:SessionContext"/>
                <soap:header use="literal" part="supportedVersions" message="tns:UniversalRecordSupportedVersions" />
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="ErrorInfoMsg">
                <soap:fault name="ErrorInfoMsg" use="literal"/>
            </fault>
            <fault name="UniversalRecordErrorInfoMsg">
                <soap:fault name="UniversalRecordErrorInfoMsg" use="literal"/>
            </fault>
        </operation>
    </binding><service name="UniversalRecordService"><port name="UniversalRecordRetrieveServicePort" binding="tns:UniversalRecordRetrieveServiceBinding">
            <soap:address location="http://localhost:8080/kestrel/UniversalRecordService"/>
        </port></service></definitions>