<?xml version="1.0" encoding="UTF-8"?>

<definitions name="UtilService"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.travelport.com/service/util_v49_0"
             xmlns:ns1="http://www.travelport.com/schema/util_v49_0"
             targetNamespace="http://www.travelport.com/service/util_v49_0">

    <import namespace="http://www.travelport.com/service/util_v49_0"
            location="UtilAbstract.wsdl"/>

    <binding name="McoCreateAgencyFeeBinding" type="tns:McoCreateAgencyFeePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="service">
            <soap:operation soapAction="http://localhost:8080/kestrel/UtilService"/>
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="ErrorInfoMsg">
                <soap:fault name="ErrorInfoMsg" use="literal" />
            </fault>
        </operation>
    </binding><service name="McoService"><port name="McoCreateAgencyFeePort" binding="tns:McoCreateAgencyFeeBinding">
            <soap:address
                    location="http://localhost:8080/kestrel/UtilService" />
        </port></service></definitions>